// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN7jUSAj8FXbI6IL4vYuJP3t4yCN2BmCA',
    appId: '1:806729412327:web:cafbd6813454940e243c42',
    messagingSenderId: '806729412327',
    projectId: 'agrodiag-ai',
    authDomain: 'agrodiag-ai.firebaseapp.com',
    storageBucket: 'agrodiag-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtKB8_6ftcUDLDIz19-Y-qS3DCzH_yomA',
    appId: '1:806729412327:android:6872b482f79566b2243c42',
    messagingSenderId: '806729412327',
    projectId: 'agrodiag-ai',
    storageBucket: 'agrodiag-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_jDanfbDMLCf-fCBLqYqAYAMo7W1hI1Y',
    appId: '1:806729412327:ios:1c956f53335b9a2e243c42',
    messagingSenderId: '806729412327',
    projectId: 'agrodiag-ai',
    storageBucket: 'agrodiag-ai.firebasestorage.app',
    iosBundleId: 'com.example.agrodiagAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_jDanfbDMLCf-fCBLqYqAYAMo7W1hI1Y',
    appId: '1:806729412327:ios:1c956f53335b9a2e243c42',
    messagingSenderId: '806729412327',
    projectId: 'agrodiag-ai',
    storageBucket: 'agrodiag-ai.firebasestorage.app',
    iosBundleId: 'com.example.agrodiagAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN7jUSAj8FXbI6IL4vYuJP3t4yCN2BmCA',
    appId: '1:806729412327:web:df2d298c9b81c44b243c42',
    messagingSenderId: '806729412327',
    projectId: 'agrodiag-ai',
    authDomain: 'agrodiag-ai.firebaseapp.com',
    storageBucket: 'agrodiag-ai.firebasestorage.app',
  );
}
